"""add audit event sequence

Revision ID: 39ebf9acec4b
Revises: 78e2625a00ae
Create Date: 2026-08-21 19:27:17.963474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ebf9acec4b'
down_revision: Union[str, Sequence[str], None] = '78e2625a00ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('event_sequence', sa.BigInteger(), sa.Identity(always=False), nullable=False))
    op.create_index(op.f('ix_audit_events_event_sequence'), 'audit_events', ['event_sequence'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_event_sequence'), table_name='audit_events')
    op.drop_column('audit_events', 'event_sequence')
    # ### end Alembic commands ###
