"""create audit events table

Revision ID: 78e2625a00ae
Revises: dc9824b15818
Create Date: 2026-08-21 18:49:33.040580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78e2625a00ae'
down_revision: Union[str, Sequence[str], None] = 'dc9824b15818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_request_id', sa.Uuid(), nullable=True),
    sa.Column('agent_action_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=150), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_action_id'], ['agent_actions.id'], name=op.f('fk_audit_events_agent_action_id_agent_actions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_request_id'], ['business_requests.id'], name=op.f('fk_audit_events_business_request_id_business_requests'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_agent_action_id'), 'audit_events', ['agent_action_id'], unique=False)
    op.create_index(op.f('ix_audit_events_business_request_id'), 'audit_events', ['business_request_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_business_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_agent_action_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
