"""add AI analysis fields to business requests

Revision ID: 84a5a8f6d76c
Revises: a0917f6597e8
Create Date: 2026-08-21 01:02:06.034165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a5a8f6d76c'
down_revision: Union[str, Sequence[str], None] = 'a0917f6597e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_requests', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('business_requests', sa.Column('priority', sa.String(length=50), nullable=True))
    op.add_column('business_requests', sa.Column('intent', sa.String(length=200), nullable=True))
    op.add_column('business_requests', sa.Column('requires_human_approval', sa.Boolean(), nullable=True))
    op.add_column('business_requests', sa.Column('recommended_action', sa.Text(), nullable=True))
    op.create_index(op.f('ix_business_requests_priority'), 'business_requests', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_requests_priority'), table_name='business_requests')
    op.drop_column('business_requests', 'recommended_action')
    op.drop_column('business_requests', 'requires_human_approval')
    op.drop_column('business_requests', 'intent')
    op.drop_column('business_requests', 'priority')
    op.drop_column('business_requests', 'category')
    # ### end Alembic commands ###
