"""add celery task id to business requests

Revision ID: a0917f6597e8
Revises: 0a85a78cdd04
Create Date: 2026-08-20 02:35:57.403070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0917f6597e8'
down_revision: Union[str, Sequence[str], None] = '0a85a78cdd04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_requests', sa.Column('celery_task_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_business_requests_celery_task_id'), 'business_requests', ['celery_task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_requests_celery_task_id'), table_name='business_requests')
    op.drop_column('business_requests', 'celery_task_id')
    # ### end Alembic commands ###
